- name: Run the create-user playbook
  ansible.builtin.import_playbook: tasks/create-user.yaml

- name: Run the boot-to-firefox playbook
  ansible.builtin.import_playbook: tasks/boot-to-firefox.yaml

- name: Run the screen-controller playbook
  ansible.builtin.import_playbook: tasks/screen-controller.yaml

- name: Run the mail-poller playbook
  ansible.builtin.import_playbook: tasks/mail-poller.yaml

- name: Run the image-processor playbook
  ansible.builtin.import_playbook: tasks/image-processor.yaml
